(() => {
  const source=window.KotizFamilyData;
  const panel=document.querySelector('#familyPanel');
  if(!source||!panel)return;
  const $=selector=>panel.querySelector(selector);
  const money=value=>new Intl.NumberFormat(document.documentElement.lang==='fr'?'fr-FR':'en-IE',{style:'currency',currency:'EUR',minimumFractionDigits:2}).format(value);
  const esc=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const copy={
    en:{members:'members',assets:'Household assets',recurring:'Monthly commitments',institutions:'institutions',held:'Total held',net:'Net worth',available:'Available savings',products:'Products',view:'View profile',all:'All',balance:'Balance',cost:'Monthly cost',debt:'Outstanding balance',owner:'Household owner',member:'Household member',adult:'Adult member',child:'Child account',guest:'Guest',shared:'Shared management',viewAccess:'View only',limited:'Limited access',base:'Main profile',subscriptions:'subscriptions'},
    fr:{members:'membres',assets:'Actifs du foyer',recurring:'Engagements mensuels',institutions:'établissements',held:'Total détenu',net:'Patrimoine net',available:'Épargne disponible',products:'Produits',view:'Voir le profil',all:'Tous',balance:'Solde',cost:'Coût mensuel',debt:'Capital restant dû',owner:'Titulaire du foyer',member:'Membre du foyer',adult:'Membre adulte',child:'Compte mineur',guest:'Invité',shared:'Gestion partagée',viewAccess:'Consultation seule',limited:'Accès limité',base:'Profil principal',subscriptions:'abonnements'}
  };
  const typeLabels={en:{banking:'Bank accounts',savings:'Savings',investments:'Investments',credits:'Credit',insurance:'Insurance',subscriptions:'Plans & subscriptions'},fr:{banking:'Comptes bancaires',savings:'Épargne',investments:'Investissements',credits:'Crédits',insurance:'Assurances',subscriptions:'Abonnements et forfaits'}};
  const statusLabels={en:{active:'Active',view:'View only',shared:'Shared',minor:'Minor',due:'Due soon',recurring:'Recurring expense'},fr:{active:'Actif',view:'Consultation seule',shared:'Partagé',minor:'Mineur',due:'Échéance proche',recurring:'Dépense récurrente'}};
  let members=source.clone(source.members),selectedId=null,filter='all';
  const lang=()=>document.documentElement.lang==='fr'?'fr':'en';
  const t=key=>copy[lang()][key];
  const roleLabel=member=>t(member.role);
  const accessLabel=member=>t(member.access==='view'?'viewAccess':member.access);
  function renderOverview(){const totals=members.reduce((acc,m)=>{const s=source.summarize(m);acc.assets+=s.assets;acc.recurring+=s.recurring;acc.institutions+=m.institutionCount;return acc;},{assets:0,recurring:0,institutions:0});$('#familyOverview').innerHTML=`<article><span>${members.length}</span><p><strong>${t('members')}</strong><small>${members.filter(m=>m.access==='shared').length} ${t('shared').toLowerCase()}</small></p></article><article><span>${money(totals.assets)}</span><p><strong>${t('assets')}</strong><small>${members.length} profils consolidés</small></p></article><article><span>${money(totals.recurring)}</span><p><strong>${t('recurring')}</strong><small>${totals.institutions} ${t('institutions')}</small></p></article>`;}
  function renderMembers(){renderOverview();$('#familyMemberList').innerHTML=members.map(member=>{const s=source.summarize(member);const subscriptions=member.products.filter(product=>product.type==='subscriptions');return `<article class="member-row member-profile-card featured-member${selectedId===member.id?' selected':''}" data-member-id="${member.id}" tabindex="0">${member.featured?`<span class="base-profile-badge">● ${t('base')}</span>`:''}<span class="member-avatar member-${member.color}">${esc(member.initial)}</span><div class="member-main"><strong>${esc(member.name)}</strong><small>${roleLabel(member)} · ${accessLabel(member)}</small><span class="member-tags"><i>${s.accounts} ${t('products').toLowerCase()}</i><i>${member.institutionCount} ${t('institutions')}</i></span></div><div class="member-subscriptions"><div><small>${subscriptions.length} ${t('subscriptions')}</small><strong>${money(subscriptions.reduce((sum,product)=>sum+(product.monthlyCost||0),0))}<span> / mo</span></strong></div><div class="subscription-stack">${subscriptions.slice(0,3).map(product=>`<span class="tone-${product.tone}" title="${esc(product.name)}">${esc(product.name.charAt(0))}</span>`).join('')}${subscriptions.length>3?`<i>+${subscriptions.length-3}</i>`:''}</div><p>${subscriptions.slice(0,3).map(product=>esc(product.name.split(' ')[0])).join(' · ')}</p></div><div class="member-worth"><small>${t('held').toUpperCase()}</small><b>${money(s.assets)}</b>${s.liabilities?`<span>${money(s.net)} ${t('net').toLowerCase()}</span>`:''}</div><button type="button" class="view-member" aria-label="${t('view')} ${esc(member.name)}">${t('view')} →</button></article>`;}).join('');}
  function renderFilters(member){const types=['all',...new Set(member.products.map(p=>p.type))];$('#productFilters').innerHTML=types.map(type=>`<button type="button" class="${filter===type?'active':''}" data-product-filter="${type}">${type==='all'?t('all'):typeLabels[lang()][type]} <span>${type==='all'?member.products.length:member.products.filter(p=>p.type===type).length}</span></button>`).join('');}
  function renderProducts(member){const products=filter==='all'?member.products:member.products.filter(p=>p.type===filter);$('#memberProducts').innerHTML=products.map(product=>{const valueLabel=product.liability?t('debt'):product.balance!==undefined?t('balance'):t('cost');const value=product.liability??product.balance??product.monthlyCost;const suffix=product.balance===undefined&&!product.liability?' / mo':'';return `<article class="member-product product-${product.type}"><span class="product-icon tone-${product.tone}">${{banking:'▤',savings:'◎',investments:'↗',credits:'−',insurance:'◇',subscriptions:'⌁'}[product.type]}</span><div class="product-copy"><span>${typeLabels[lang()][product.type]}</span><strong>${esc(product.name)}</strong><small>${esc(product.institution)}</small></div><div class="product-indicator"><i></i><span>${esc(product.indicator)}</span></div><div class="product-value"><small>${valueLabel}</small><strong>${money(value)}${suffix}</strong></div><div class="product-statuses">${product.status.map(status=>`<span class="status-${status}">${statusLabels[lang()][status]}</span>`).join('')}</div></article>`;}).join('');}
  function renderDetail(){const member=members.find(item=>item.id===selectedId);if(!member)return;const s=source.summarize(member);$('#detailAvatar').className=`member-avatar member-${member.color}`;$('#detailAvatar').textContent=member.initial;$('#detailName').textContent=member.name;$('#detailRole').textContent=roleLabel(member).toUpperCase();$('#detailAccess').textContent=`${accessLabel(member)} · ${lang()==='fr'?'Synchronisé aujourd’hui':'Synced today'}`;$('#memberSummary').innerHTML=`<article><span>${t('held')}</span><strong>${money(s.assets)}</strong><small>${member.institutionCount} ${t('institutions')}</small></article><article><span>${t('available')}</span><strong>${money(s.available)}</strong><small>${lang()==='fr'?'Livrets et projets':'Savings and projects'}</small></article><article><span>${t('recurring')}</span><strong>${money(s.recurring)}</strong><small>${lang()==='fr'?'Par mois':'Per month'}</small></article><article><span>${t('products')}</span><strong>${s.accounts}</strong><small>${s.liabilities?`${money(s.liabilities)} ${lang()==='fr'?'de crédit':'in credit'}`:lang()==='fr'?'Aucun crédit':'No credit'}</small></article>`;const groups=['banking','savings','investments'].map(type=>({type,value:member.products.filter(p=>p.type===type).reduce((sum,p)=>sum+(p.balance||0),0)})).filter(group=>group.value);const total=groups.reduce((sum,g)=>sum+g.value,0)||1;$('#assetAllocation').innerHTML=`<div><span>${lang()==='fr'?'RÉPARTITION DES ACTIFS':'ASSET ALLOCATION'}</span><div class="allocation-bar">${groups.map(g=>`<i class="allocation-${g.type}" style="width:${g.value/total*100}%"></i>`).join('')}</div></div><div class="allocation-legend">${groups.map(g=>`<span><i class="allocation-${g.type}"></i>${typeLabels[lang()][g.type]} <b>${Math.round(g.value/total*100)}%</b></span>`).join('')}</div>`;renderFilters(member);renderProducts(member);}
  function openMember(id){selectedId=id;filter='all';renderMembers();renderDetail();$('#memberDetail').hidden=false;$('#familyMemberList').hidden=true;$('#familyOverview').hidden=true;$('#familyHint').hidden=true;$('#memberDetail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
  function closeDetail(){selectedId=null;$('#memberDetail').hidden=true;$('#familyMemberList').hidden=false;$('#familyOverview').hidden=false;$('#familyHint').hidden=false;renderMembers();}
  $('#toggleMemberForm').addEventListener('click',()=>{const form=$('#memberForm');form.hidden=!form.hidden;$('#toggleMemberForm').setAttribute('aria-expanded',String(!form.hidden));if(!form.hidden)$('#memberName').focus();});
  $('#closeMemberForm').addEventListener('click',()=>{$('#memberForm').hidden=true;$('#toggleMemberForm').setAttribute('aria-expanded','false');});
  $('#memberForm').addEventListener('submit',event=>{event.preventDefault();const name=$('#memberName').value.trim();if(!name)return;const role=$('#memberRole').value;const access=$('#memberAccess').value;const color=$('#memberColor').value;members.push({id:`member-${Date.now()}`,name,initial:name[0].toUpperCase(),color,role,access,institutionCount:1,products:[{id:`current-${Date.now()}`,name:lang()==='fr'?'Compte courant à connecter':'Current account to connect',type:'banking',institution:'Kotiz Demo',balance:750,status:['view'],indicator:lang()==='fr'?'Synchronisation disponible':'Sync available',tone:'blue'},{id:`goal-${Date.now()}`,name:lang()==='fr'?'Épargne projet':'Savings goal',type:'savings',institution:'Kotiz Objectifs',balance:250,status:['shared'],indicator:lang()==='fr'?'25 % de l’objectif':'25% of goal',tone:'purple'}]});event.target.reset();event.target.hidden=true;$('#toggleMemberForm').setAttribute('aria-expanded','false');renderMembers();openMember(members.at(-1).id);});
  $('#familyMemberList').addEventListener('click',event=>{const row=event.target.closest('[data-member-id]');if(row)openMember(row.dataset.memberId);});
  $('#familyMemberList').addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.closest('[data-member-id]')){event.preventDefault();openMember(event.target.closest('[data-member-id]').dataset.memberId);}});
  $('#closeMemberDetail').addEventListener('click',closeDetail);
  $('#productFilters').addEventListener('click',event=>{const button=event.target.closest('[data-product-filter]');if(!button)return;filter=button.dataset.productFilter;renderFilters(members.find(m=>m.id===selectedId));renderProducts(members.find(m=>m.id===selectedId));});
  document.querySelector('.language-toggle')?.addEventListener('click',()=>setTimeout(()=>{renderMembers();if(selectedId)renderDetail();},0));
  renderMembers();
})();
